AWSTemplateFormatVersion: '2010-09-09'
Resources:
  ASGTagger:
    Properties:
      CodeUri: s3://sahaj-lambda/LUAU/94714be71ee4ec6b994f69dd67f96bdc
      Events:
        ASGCreatedEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail:
                eventName:
                  - CreateAutoScalingGroup
                eventType: AwsApiCall      
      Handler: tagger/asg_tagger.lambda_handler
      Policies:
      - AWSLambdaExecute
      - Statement:
        - Action:
          - ec2:DescribeInstances
          - ec2:CreateTags
          - autoscaling:DescribeAutoScalingGroups
          - autoscaling:DescribeAutoScalingInstances
          - autoscaling:CreateOrUpdateTags
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
      Runtime: python3.6
    Type: AWS::Serverless::Function
  EC2Tagger:
    Properties:
      CodeUri: s3://sahaj-lambda/LUAU/94714be71ee4ec6b994f69dd67f96bdc
      Events:
        EC2ResourceCreatedEvent:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              detail:
                eventName:
                  - RunInstances
                  - CreateImage
                  - CreateVolume
                  - CreateSecurityGroup
                eventType: AwsApiCall
      Handler: tagger/ec2_tagger.lambda_handler
      Policies:
      - AWSLambdaExecute
      - Statement:
        - Action:
          - ec2:CreateTags
          - ec2:DescribeInstances
          - autoscaling:DescribeAutoScalingGroups
          - autoscaling:DescribeAutoScalingInstances
          Effect: Allow
          Resource: '*'
        Version: '2012-10-17'
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
